name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy preview
        id: preview-step
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs/
          preview-branch: main
          pages-base-path: docs/

      - run: echo "${{ steps.preview-step.outputs }}"
      - if: steps.preview-step.outputs.deployment-action == 'deploy'
        run: echo "Preview visible at ${{ steps.preview-step.outputs.preview-url }}"
